Add typescript templates
serverless-components/express pull request #39
Opened 2020-09-20 21:37 UTC by zackdotcomputer

Adds two templates showing how to use this component in typescript with either the vanilla tsc or with webpack as your compiler/bundler.

This was done to explore whether it was even possible after reading #12

2020-11-18 15:59 UTC, eahefnawy requested changes
Thanks for the PR! DId you face any issues getting it to work with TypeScript?

2020-11-18 15:59 UTC, eahefnawy commented on templates/express-starter-typescript-tsc/serverless.yml
> +name: express-starter
could you change that to `express-starter-typescript-tsc`?

2020-11-18 15:59 UTC, eahefnawy commented on templates/express-starter-typescript-webpack/serverless.yml
> +name: express-starter
could you change that to `express-starter-typescript-webpack`?

2020-11-18 17:12 UTC, zackdotcomputer commented
@eahefnawy Not at all - was able to pipe the existing templates through tsc or webpack just fine and, once I added the typing, everything seemed to work ok.

Made the changes you requested and fixed the lint/prettier issues that the GH Action turned up

2020-11-20 12:10 UTC, eahefnawy approved these changes
Thank you 🙏

2020-11-20 12:10 UTC, merged